version: '3.8'

services:
  app:
    container_name: e-commerce
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=mysql://sagarika:Sagarika@%71@mysql-db:3306/eCommerce
      - DBUSER=sagarika
      - PASSWORD=Sagarika@%71
      - DBNAME=eCommerce
      - DB_PORT=3306
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped
    
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Sagarika@%71
      MYSQL_DATABASE: e-Commerce
      MYSQL_USER: sagarika
      MYSQL_PASSWORD: Sagarika@%71
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "sagarika", "-Sagarika@%71"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql-data: