version: "3.8"

services:
  app:
    container_name: e-commerce
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL="mongodb+srv://sagarikar:Z3t9l5bWhpopSev8@sagarika.lr41m.mongodb.net/e-commerce"
      - JWT_SECRET_KEY="kdhjfjiireugujjdhfhfddhshahhyryuriiututruueuhhfhhhhdvfbqqola,m"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - my_network
    ports:
      - "3000:3000"

networks:
  my_network:
    driver: bridge
